## Datastructures

Welcome to the second exercise in Einführung in Visual Computing. This exercise gives you a basic knowledge and understanding of python and commonly used libraries. It consists of four parts, each one includes a Jupyter-Notebook as well as a python file where you are expected to contribute the missing functions.

The Jupyter Notebook provides the general program sequence, once everything is implemented, you should see results as described in the main task description.

The first part is all about numpy, so we will deal with np.arrays. We can define vectors, matrices or even arrays of higher dimension with numpy. It also provides powerful functionalities of linear algebra as well as mathematical functions. Make sure you check out the numpy documentation in case you want to have a deeper look into it.

----

First, we import everything we will need to run the code. We will use the package autoreload to reload the changes done in the files automatically. This is followed by the general import commands (import datastructures) to make use of functions defined in datastructures.py 

You can also import other libraries like e.g., 

- numpy, commonly used as '''import numpy as np''' enabling us to use numpy functions via np.xxxx
- matplotlib, mostly imported as '''import matplotlib.pyplot as plt'''

In [1]:
%load_ext autoreload
%autoreload 1
%aimport datastructures
import datastructures

-----

To start our exercise, we first want to define some arrays we are working with. Implement define_structures in the file datastructures. The two vectors v1 and v2 and the matrix M are defined by your matriculation number. (Refer to the task description)

Once this is done, we are printing the np.arrays below. They are now in our working space and we can operate on them.

**Note:** NumPy may display floating-point numbers like $1.0$ as $1.$ in its output. This is only a formatting difference in the display and represents the same numerical value, so the result is still considered correct.

In [2]:
v1, v2, M = datastructures.define_structures()
print(f"v1 : {v1}")
print(f"v2 : {v2}")
print(f"M : {M}")

v1 : [2 1 5]
v2 : [1 2 7]
M : [[2 2 5]
 [2 8 1]
 [7 4 1]]


-----

Now, we generate a sequence with step size 0.25 from the minimum and maximum of matrix M. Implement this in the function sequence().

In [3]:
seq = datastructures.sequence(M)
print(seq)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.  ]


-----

Last but not least, we can also define block matrices or other more complex arrays. Implement the 15x9 matrix we are calling 'mm' down below and check if the output matches the task description!

In [8]:
mm = datastructures.matrix(M)
print(mm.shape)
print(mm)

(15, 9)
[[2 2 5 0 0 0 2 2 5]
 [2 8 1 0 0 0 2 8 1]
 [7 4 1 0 0 0 7 4 1]
 [0 0 0 2 2 5 0 0 0]
 [0 0 0 2 8 1 0 0 0]
 [0 0 0 7 4 1 0 0 0]
 [2 2 5 0 0 0 2 2 5]
 [2 8 1 0 0 0 2 8 1]
 [7 4 1 0 0 0 7 4 1]
 [0 0 0 2 2 5 0 0 0]
 [0 0 0 2 8 1 0 0 0]
 [0 0 0 7 4 1 0 0 0]
 [2 2 5 0 0 0 2 2 5]
 [2 8 1 0 0 0 2 8 1]
 [7 4 1 0 0 0 7 4 1]]


### Implementation of numpy-functions

For the next exercise you have to implement some useful functions of numpy yourself, without using the actual numpy functions!

First we want to implement the function dot_product(v1,v2) that computes the dot-product of two 3-element vectors. 

In [9]:
dot = datastructures.dot_product(v1, v2)
print(dot)

39


----

To proceed we are going to implement the function cross_product(v1,v2) that computes the cross-product of two 3-element vectors.

In [10]:
cross = datastructures.cross_product(v1, v2)
print(cross)

[-3 -9  3]


----

Now we want to make the computation more general and replace one vector with a matrix. In this task we are going to implement the function vector_X_matrix(v,M) that multiplies a 3-element vector from the left with a 3x3 matrix.

In [11]:
vec_X_mat = datastructures.vector_X_matrix(v1, M)
print(vec_X_mat)

[41 32 16]


----

Next we are going to perform a similar multiplication but from the other side. The function matrix_X_vector(v,M) multiplies a 3-element vector from the right with a 3x3 matrix.

In [12]:
mat_X_vec = datastructures.matrix_X_vector(M, v2)
print(mat_X_vec)

[41 25 22]


----

In this task we are going to replace both vectors with matrices. The function matrix_X_matrix(M1,M2) multiplies two 3x3 matrices. M2 should be multiplied from the left with M1.

In [13]:
mat_X_mat = datastructures.matrix_X_matrix(M, M.transpose())
print(mat_X_mat)

[[33 25 27]
 [25 69 47]
 [27 47 66]]


----

In the end of this exercise we are going to perform a different way of multiplying two matrices. The function matrix_Xc_matrix(M1,M2) multiplies the matrices M1 and M2 componentwise (Hadamard-product). Hence, every element of M1 is going to be multiplied with every element of M2 that has the same coordinate.

In [14]:
mat_Xc_mat = datastructures.matrix_Xc_matrix(M, M.transpose())
print(mat_Xc_mat)

[[ 4  4 35]
 [ 4 64  4]
 [35  4  1]]
